import type { Metadata } from 'next'
// eslint-disable-next-line camelcase
import { Inter, JetBrains_Mono } from 'next/font/google'
import './globals.css'
import { cn } from '@/services/utils/className'
import { EventProvider } from '@/contexts/Event'
import { MusicProvider } from '@/contexts/Music'
import BackgroundSwitch from '@/components/organisms/BackgroundSwitch'
import MusicPlayer from '@/components/molecules/MusicPlayer'

export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'pt' }]
}

type Props = {
  params: {
    lang: 'en' | 'pt'
  }
  children: React.ReactNode
}

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-jetbrains-mono',
})

export const metadata: Metadata = {
  title: "Miller's time",
  description: 'Generated by create next app',
}

export default function RootLayout({ children, params }: Props) {
  return (
    <html lang={params.lang}>
      <body
        className={cn(
          'overflow-hidden bg-void',
          inter.variable,
          jetbrainsMono.variable,
        )}
      >
        <BackgroundSwitch />
        <div className="absolute inset-0 bg-black/60" />
        {/* Star particles layer */}
        <div
          className="pointer-events-none absolute inset-0 animate-twinkle"
          style={{
            backgroundImage: [
              'radial-gradient(1px 1px at 20% 30%, rgba(255,255,255,0.3), transparent)',
              'radial-gradient(1px 1px at 80% 10%, rgba(255,255,255,0.2), transparent)',
              'radial-gradient(1px 1px at 50% 60%, rgba(255,255,255,0.15), transparent)',
              'radial-gradient(1px 1px at 10% 80%, rgba(255,255,255,0.2), transparent)',
              'radial-gradient(1px 1px at 90% 50%, rgba(255,255,255,0.15), transparent)',
              'radial-gradient(1.5px 1.5px at 30% 70%, rgba(212,160,74,0.4), transparent)',
              'radial-gradient(1px 1px at 60% 90%, rgba(255,255,255,0.2), transparent)',
              'radial-gradient(1.5px 1.5px at 75% 35%, rgba(212,160,74,0.3), transparent)',
            ].join(', '),
          }}
        />
        {/* Ambient glow */}
        <div
          className="pointer-events-none absolute inset-0"
          style={{
            background:
              'radial-gradient(ellipse 80% 50% at 50% 20%, rgba(212,160,74,0.06) 0%, transparent 60%)',
          }}
        />
        <div className="h-screen overflow-y-scroll">
          <MusicProvider>
            <EventProvider>{children}</EventProvider>
            <MusicPlayer />
          </MusicProvider>
        </div>
      </body>
    </html>
  )
}
