import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/services/utils/className'
import { EventProvider } from '@/contexts/Event'
import { MusicProvider } from '@/contexts/Music'
import BackgroundSwitch from '@/components/organisms/BackgroundSwitch'

export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'pt' }]
}

type Props = {
  params: {
    lang: 'en' | 'pt'
  }
  children: React.ReactNode
}

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: "Miller's time",
  description: 'Generated by create next app',
}

export default function RootLayout({ children, params }: Props) {
  return (
    <html lang={params.lang}>
      <body className={cn('', inter.variable)}>
        <BackgroundSwitch />
        <div className="absolute inset-0 bg-black opacity-40" />
        <div className="h-screen overflow-y-scroll">
          <MusicProvider>
            <EventProvider>{children}</EventProvider>
          </MusicProvider>
        </div>
      </body>
    </html>
  )
}
